package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

var file *os.File

const migrationFile = `// Code generated by lesiw.io/plain. DO NOT EDIT.

package main

import (
	"embed"

	"lesiw.io/plain"
)

//go:embed sql/migrations/*
var migrations embed.FS

func migrate() error {
	return plain.Migrate(migrations)
}
`

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "failed to generate stmts.go: %s\n", err)
		os.Exit(1)
	}
}

func run() error {
	err := os.WriteFile("migration.go", []byte(migrationFile), 0644)
	if err != nil {
		return fmt.Errorf("failed to write migration.go: %w", err)
	}
	if err = os.MkdirAll("internal/stmt", 0755); err != nil {
		return fmt.Errorf("failed to create internal/stmt/ directory: %w", err)
	}
	file, err = os.OpenFile("internal/stmt/stmts.go",
		os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		return fmt.Errorf("failed to create stmts.go: %w", err)
	}
	defer file.Close()
	_, _ = file.WriteString(
		"// Code generated by lesiw.io/plain. DO NOT EDIT.\n\n")
	_, _ = file.WriteString("package stmt\n")
	return filepath.WalkDir("sql/statements", walkFunc)
}

func walkFunc(path string, d os.DirEntry, err error) error {
	if err != nil {
		return err
	}
	if d.IsDir() {
		return nil
	}
	f, err := os.Open(path)
	if err != nil {
		return fmt.Errorf("failed to read file: %w", err)
	}
	b := &strings.Builder{}
	_, _ = io.Copy(b, f)
	_, _ = file.WriteString(fmt.Sprintf(
		"\nconst %s = `\n%s`\n",
		name(d.Name()),
		b.String(),
	))
	return nil
}

func name(s string) string {
	s, _, _ = strings.Cut(s, ".")
	var b strings.Builder
	upper := true
	for _, r := range s {
		if r == '-' || r == '_' {
			upper = true
			continue
		}
		if upper || unicode.IsUpper(r) {
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			b.WriteRune(unicode.ToLower(r))
		}
	}
	return b.String()
}
